import { User } from "../types/types";

export const mockUsers: User[] = [
  {
    id: 1,
    name: "Maria Silva",
    email: "maria@exemplo.com",
    password: "senha123",
    city: "São Paulo",
    state: "SP",
    role: "USER",
    cpf: "123.456.789-00",
    age: 28,
    avatar: "https://randomuser.me/api/portraits/lego/1.jpg",
  },
  {
    id: 2,
    name: "João Souza",
    email: "joao@exemplo.com",
    password: "senha456",
    city: "Rio de Janeiro",
    state: "RJ",
    role: "USER",
    cpf: "987.654.321-00",
    age: 34,
    avatar: "https://randomuser.me/api/portraits/lego/2.jpg",
  },
  {
    id: 3,
    name: "ONG Patinhas Felizes",
    email: "contato@patinhasfelizes.org",
    password: "ong123",
    city: "Belo Horizonte",
    state: "MG",
    role: "ONG",
    cnpj: "12.345.678/0001-99",
    description: "ONG dedicada ao resgate e adoção de animais.",
    avatar: "https://randomuser.me/api/portraits/lego/3.jpg",
  },
  {
    id: 4,
    name: "ONG Amigos dos Animais",
    email: "amigos@onganimais.org",
    password: "amigos456",
    city: "Curitiba",
    state: "PR",
    role: "ONG",
    cnpj: "98.765.432/0001-11",
    description: "Acolhimento e adoção responsável de pets.",
    avatar: "https://randomuser.me/api/portraits/lego/4.jpg",
  },
  {
    id: 5,
    name: "Ana Paula",
    email: "ana@exemplo.com",
    password: "ana789",
    city: "Fortaleza",
    state: "CE",
    role: "USER",
    cpf: "321.654.987-00",
    age: 22,
    avatar: "https://randomuser.me/api/portraits/lego/5.jpg",
  },
   {
    id: 6,
    name: "teste",
    email: "teste@exemplo.com",
    password: "teste123",
    city: "Fortaleza",
    state: "CE",
    role: "USER",
    cpf: "321.654.987-00",
    age: 22,
    avatar: "https://randomuser.me/api/portraits/lego/5.jpg",
  },
];
